# Generated by Django 3.0.8 on 2020-08-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
