# Generated by Django 3.0.8 on 2020-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerItem', '0002_remove_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=20),
        ),
    ]
