# Generated by Django 3.0.8 on 2020-08-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registerItem', '0004_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='availability',
        ),
        migrations.AddField(
            model_name='item',
            name='counting',
            field=models.CharField(choices=[('Available', 'Available'), ('Given', 'Given')], default='Given', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Given', 'Given')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='device',
            field=models.OneToOneField(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registerItem.Stock'),
        ),
    ]
